### ISSUE TITLE
createMutableImage does not initialize background

### ISSUE THREAD

**Issue by bigsleep** [Twinside/Juicy.Pixels#112]
I tried to create some images by using MutableImage. It seems createMutableImage does not initialize image data in some cases.

Code to reproduce:
https://gist.github.com/bigsleep/aacf04f68849a845c8d4

version:
JuicyPixels 3.2.6.1.

Generated images:
![test0](https://cloud.githubusercontent.com/assets/544115/11455116/105220ce-9690-11e5-8545-858f8f616590.png)
![test1](https://cloud.githubusercontent.com/assets/544115/11455117/16567e3e-9690-11e5-85d8-82410b105ebc.png)
![test100](https://cloud.githubusercontent.com/assets/544115/11455118/1c019666-9690-11e5-87d1-61fccd00abe4.png)

**Comment by Twinside** [comment]
GHC version, platform, 64 or 32 bits?

**Comment by bigsleep** [comment]
GHC version: 7.10.2, 64 bits

I used stack to build the code.

This is the list of dependencies.
JuicyPixels 3.2.6.1
array 0.5.1.0
base 4.8.1.0
binary 0.7.5.0
bytestring 0.10.6.0
containers 0.5.6.2
deepseq 1.4.1.1
ghc-prim 0.4.0.0
integer-gmp 1.0.0.0
mtl 2.2.1
primitive 0.6.1.0
reproduce 0.1.0.0
transformers 0.4.2.0
vector 0.10.12.3
zlib 0.5.4.2


https://gist.github.com/bigsleep/aacf04f68849a845c8d4
In this code, I tried to draw a green square on each images in deferent positions.
Though, generated images were different from what I expected.
It seems previous generated image data remaining on latter generated images.

**Comment by Twinside** [comment]
`createMutableImage` has an inline annotation which is nasty in this case because it seems to allow sharing

As a temporary workaround:

~~~~{.haskell}
createMutable' :: Int -> Int -> PixelRGBA8 -> IO (MutableImage (PrimState IO) PixelRGBA8)
{-# NOINLINE createMutable' #-}
createMutable' w h back = createMutableImage w h back

writeOneRectImage :: (Int, Int) -> Int -> IO ()
writeOneRectImage (w, h) i = do
   img <- createMutable' w h background
   {-img <- createMutableImage w h background-}
 -- ...
~~~~

**Comment by bigsleep** [comment]
Thanks!
I will use the workaround for now.

**Comment by Twinside** [comment]
Should be ok with version [3.2.6.3](http://hackage.haskell.org/package/JuicyPixels-3.2.6.3)
