### ISSUE TITLE
Reading JPEG fails?

### ISSUE THREAD

**Issue by phadej** [Twinside/Juicy.Pixels#134]
See https://github.com/phadej/JuicyPixels-scale-dct/issues/4

There is a test image, if I do a simple conversion:
```hs
test = do
    Right dimg <- readImage "cat.png
    let img = convertRGBA8 dimg
    writePng "tmp.png" img
```
I'll get cyan/blue image as in the report.

Is there a way to debug that?

**Comment by nek0** [comment]
I can confirm that test working. I wrote the following code:
```Haskell
import Codec.Picture
import Codec.Picture.ScaleDCT

main :: IO ()
main = do
  Right dtest1 <- readImage "cat.jpg"
  Right dtest2 <- readImage "cat.png"
  let test1 = convertRGBA8 dtest1
      test2 = convertRGBA8 dtest2
  writePng "test1.png" test1
  writePng "test2.png" test2
```

The resulting picture `test1.png` is garbled, whereas `test2.png` is perfectly fine.

This bug seems to have something to do with the file size of the jpeg image that's being read. I have other jpegs in my gallery, which also have been processed with this library, but are not garbled. All they have in common is, that they are smaller in size.

**Comment by Twinside** [comment]
Reproduced, I'll have a look

**Comment by Twinside** [comment]
I hate progressive Jpeg so much it's not even funny. Updated package uploaded to Hackage, version 3.2.8

**Comment by nek0** [comment]
thanks a lot.
